### ISSUE TITLE
Error specifying directory with remote-dir

### ISSUE THREAD

**Issue by sandersonsoares** [airvzxf/ftp-deployment-action#1]
when specifying the server's directory, it gives error for actually existing files there. Wouldn't it be possible to overwrite the files in the specified directory?

following the logs he tries to create the directory instead of accessing it. I could try to create it just in case the directory doesn't exist.

**Comment by airvzxf** [comment]
Hi Sanderson Soares,
Could you provide me the link of your repository where this error occurred? If you have the specific action ID (#), can be better.

**Comment by airvzxf** [comment]
I'll close this issue since there is no more information. Furthermore, it is an old comment.
