### ISSUE TITLE
Unable to find version `latest`

### ISSUE THREAD

**Issue by B1GabrielAugusto** [airvzxf/ftp-deployment-action#10]
I tried running the Action and got the following error message:

```Error: Unable to resolve action `airvzxf/ftp-deployment-action@latest`, unable to find version `latest```

Probably due to a recent commit, because yesterday, it worked fine.

**Comment by airvzxf** [comment]
Yes, it should be for the yesterday commits. I fixed, please check it.

**Comment by B1GabrielAugusto** [comment]
Yes, it worked. Thanks.
